-- SISU - Modulo de inventario y prestamos de implementos deportivos
-- Ejecutar una sola vez en Supabase SQL Editor sobre una base SISU existente.


-- =========================
-- IMPLEMENTOS DEPORTIVOS / BIENESTAR
-- =========================
CREATE TABLE IF NOT EXISTS public.implementos_deportivos (
    id_implemento BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(50) NOT NULL UNIQUE,
    nombre VARCHAR(120) NOT NULL,
    categoria VARCHAR(50) NOT NULL DEFAULT 'Otro',
    descripcion TEXT,
    cantidad_total INTEGER NOT NULL DEFAULT 1 CHECK (cantidad_total > 0),
    cantidad_disponible INTEGER NOT NULL DEFAULT 1 CHECK (cantidad_disponible >= 0),
    ubicacion VARCHAR(120),
    estado VARCHAR(20) NOT NULL DEFAULT 'Activo'
        CHECK (estado IN ('Activo','Mantenimiento','Inactivo')),
    fecha_registro TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    creado_por BIGINT REFERENCES public.usuarios(id_usuario) ON DELETE SET NULL,
    CONSTRAINT implementos_disponibilidad_check CHECK (cantidad_disponible <= cantidad_total)
);

CREATE TABLE IF NOT EXISTS public.prestamos_implementos (
    id_prestamo BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_implemento BIGINT NOT NULL REFERENCES public.implementos_deportivos(id_implemento) ON DELETE RESTRICT,
    id_estudiante BIGINT NOT NULL REFERENCES public.usuarios(id_usuario) ON DELETE RESTRICT,
    cantidad INTEGER NOT NULL DEFAULT 1 CHECK (cantidad > 0),
    fecha_prestamo TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    fecha_devolucion TIMESTAMPTZ,
    prestado_por BIGINT NOT NULL REFERENCES public.usuarios(id_usuario) ON DELETE RESTRICT,
    recibido_por BIGINT REFERENCES public.usuarios(id_usuario) ON DELETE SET NULL,
    observaciones_salida TEXT,
    observaciones_entrega TEXT,
    estado VARCHAR(20) NOT NULL DEFAULT 'Prestado'
        CHECK (estado IN ('Prestado','Devuelto','Cancelado')),
    CONSTRAINT prestamo_fechas_check CHECK (fecha_devolucion IS NULL OR fecha_devolucion >= fecha_prestamo)
);

CREATE INDEX IF NOT EXISTS idx_prestamos_implementos_estado ON public.prestamos_implementos(estado);
CREATE INDEX IF NOT EXISTS idx_prestamos_implementos_estudiante ON public.prestamos_implementos(id_estudiante);
CREATE INDEX IF NOT EXISTS idx_prestamos_implementos_item ON public.prestamos_implementos(id_implemento);
CREATE INDEX IF NOT EXISTS idx_prestamos_implementos_fecha ON public.prestamos_implementos(fecha_prestamo DESC);


CREATE OR REPLACE FUNCTION public.registrar_prestamo_implemento(
 p_id_implemento bigint,
 p_id_estudiante bigint,
 p_cantidad integer DEFAULT 1,
 p_observaciones text DEFAULT NULL
) RETURNS bigint
LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE
 uid bigint;
 rol bigint;
 disponible integer;
 estado_item text;
 rol_estudiante bigint;
 prestamo_id bigint;
BEGIN
 uid:=public.mi_usuario_id();
 rol:=public.mi_rol();
 IF uid IS NULL OR rol NOT IN (1,7) THEN RAISE EXCEPTION 'Sin permiso para registrar préstamos'; END IF;
 IF p_cantidad IS NULL OR p_cantidad<=0 THEN RAISE EXCEPTION 'Cantidad inválida'; END IF;

 SELECT cantidad_disponible,estado INTO disponible,estado_item
 FROM public.implementos_deportivos
 WHERE id_implemento=p_id_implemento
 FOR UPDATE;

 IF disponible IS NULL THEN RAISE EXCEPTION 'Implemento no encontrado'; END IF;
 IF estado_item<>'Activo' THEN RAISE EXCEPTION 'El implemento no está habilitado para préstamo'; END IF;
 IF disponible<p_cantidad THEN RAISE EXCEPTION 'No hay suficientes unidades disponibles'; END IF;

 SELECT id_rol INTO rol_estudiante
 FROM public.usuarios
 WHERE id_usuario=p_id_estudiante AND estado='Activo';

 IF rol_estudiante IS DISTINCT FROM 3 THEN RAISE EXCEPTION 'El usuario seleccionado no es un estudiante activo'; END IF;

 UPDATE public.implementos_deportivos
 SET cantidad_disponible=cantidad_disponible-p_cantidad
 WHERE id_implemento=p_id_implemento;

 INSERT INTO public.prestamos_implementos(
  id_implemento,id_estudiante,cantidad,prestado_por,observaciones_salida,estado
 ) VALUES(
  p_id_implemento,p_id_estudiante,p_cantidad,uid,NULLIF(TRIM(p_observaciones),''),'Prestado'
 ) RETURNING id_prestamo INTO prestamo_id;

 RETURN prestamo_id;
END $$;

CREATE OR REPLACE FUNCTION public.registrar_devolucion_implemento(
 p_id_prestamo bigint,
 p_observaciones text DEFAULT NULL
) RETURNS void
LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE
 uid bigint;
 rol bigint;
 item_id bigint;
 qty integer;
BEGIN
 uid:=public.mi_usuario_id();
 rol:=public.mi_rol();
 IF uid IS NULL OR rol NOT IN (1,7) THEN RAISE EXCEPTION 'Sin permiso para registrar devoluciones'; END IF;

 SELECT id_implemento,cantidad INTO item_id,qty
 FROM public.prestamos_implementos
 WHERE id_prestamo=p_id_prestamo AND estado='Prestado'
 FOR UPDATE;

 IF item_id IS NULL THEN RAISE EXCEPTION 'Préstamo activo no encontrado'; END IF;

 UPDATE public.prestamos_implementos
 SET estado='Devuelto',
     fecha_devolucion=NOW(),
     recibido_por=uid,
     observaciones_entrega=NULLIF(TRIM(p_observaciones),'')
 WHERE id_prestamo=p_id_prestamo;

 UPDATE public.implementos_deportivos
 SET cantidad_disponible=LEAST(cantidad_total,cantidad_disponible+qty)
 WHERE id_implemento=item_id;
END $$;

REVOKE ALL ON FUNCTION public.registrar_prestamo_implemento(bigint,bigint,integer,text) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.registrar_devolucion_implemento(bigint,text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.registrar_prestamo_implemento(bigint,bigint,integer,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.registrar_devolucion_implemento(bigint,text) TO authenticated;


-- Seguridad del módulo de implementos deportivos
ALTER TABLE public.implementos_deportivos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.prestamos_implementos ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS implementos_deportivos_read ON public.implementos_deportivos;
DROP POLICY IF EXISTS implementos_deportivos_insert ON public.implementos_deportivos;
DROP POLICY IF EXISTS implementos_deportivos_update ON public.implementos_deportivos;
DROP POLICY IF EXISTS implementos_deportivos_delete ON public.implementos_deportivos;
DROP POLICY IF EXISTS prestamos_implementos_read ON public.prestamos_implementos;

CREATE POLICY implementos_deportivos_read
ON public.implementos_deportivos FOR SELECT TO authenticated
USING (public.mi_rol() IN (1,7));

CREATE POLICY implementos_deportivos_insert
ON public.implementos_deportivos FOR INSERT TO authenticated
WITH CHECK (public.mi_rol() IN (1,7));

CREATE POLICY implementos_deportivos_update
ON public.implementos_deportivos FOR UPDATE TO authenticated
USING (public.mi_rol() IN (1,7))
WITH CHECK (public.mi_rol() IN (1,7));

CREATE POLICY implementos_deportivos_delete
ON public.implementos_deportivos FOR DELETE TO authenticated
USING (public.mi_rol()=1);

CREATE POLICY prestamos_implementos_read
ON public.prestamos_implementos FOR SELECT TO authenticated
USING (public.mi_rol() IN (1,7));

REVOKE ALL ON TABLE public.implementos_deportivos FROM anon,authenticated;
REVOKE ALL ON TABLE public.prestamos_implementos FROM anon,authenticated;
GRANT SELECT,INSERT,UPDATE,DELETE ON TABLE public.implementos_deportivos TO authenticated;
GRANT SELECT ON TABLE public.prestamos_implementos TO authenticated;
GRANT USAGE,SELECT ON SEQUENCE public.implementos_deportivos_id_implemento_seq TO authenticated;
