-- SISU: ejecutar primero database/bd.sql en un proyecto Supabase nuevo y luego este archivo.
ALTER TABLE public.usuarios ADD COLUMN IF NOT EXISTS auth_user_id uuid UNIQUE REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.usuarios ALTER COLUMN password DROP NOT NULL;
-- Retirar completamente el rol y el tipo de consulta eliminados.
UPDATE public.consultas SET tipo_consulta = NULL WHERE tipo_consulta IS NOT NULL AND tipo_consulta NOT IN ('Enfermería','Medicina General');
ALTER TABLE public.consultas DROP CONSTRAINT IF EXISTS consultas_tipo_consulta_check;
ALTER TABLE public.consultas ADD CONSTRAINT consultas_tipo_consulta_check
CHECK (tipo_consulta IS NULL OR tipo_consulta IN ('Enfermería','Medicina General'));
UPDATE public.usuarios SET id_rol = NULL WHERE id_rol IS NOT NULL AND id_rol NOT IN (1,2,3,4,5,7);
DELETE FROM public.roles WHERE id_rol NOT IN (1,2,3,4,5,7);
CREATE UNIQUE INDEX IF NOT EXISTS inventario_codigo_unique ON public.inventario(codigo) WHERE codigo IS NOT NULL;
CREATE INDEX IF NOT EXISTS usuarios_auth_user_idx ON public.usuarios(auth_user_id);
-- Flujo secuencial de incapacidades: radicación -> Enfermería -> Coordinación
ALTER TABLE public.incapacidades ADD COLUMN IF NOT EXISTS radicada_por BIGINT REFERENCES public.usuarios(id_usuario) ON DELETE SET NULL;
ALTER TABLE public.incapacidades ADD COLUMN IF NOT EXISTS revisada_enfermeria_por BIGINT REFERENCES public.usuarios(id_usuario) ON DELETE SET NULL;
ALTER TABLE public.incapacidades ADD COLUMN IF NOT EXISTS fecha_revision_enfermeria TIMESTAMPTZ;
ALTER TABLE public.incapacidades ADD COLUMN IF NOT EXISTS observacion_enfermeria TEXT;
ALTER TABLE public.incapacidades ADD COLUMN IF NOT EXISTS revisada_coordinacion_por BIGINT REFERENCES public.usuarios(id_usuario) ON DELETE SET NULL;
ALTER TABLE public.incapacidades ADD COLUMN IF NOT EXISTS fecha_revision_coordinacion TIMESTAMPTZ;
ALTER TABLE public.incapacidades ADD COLUMN IF NOT EXISTS observacion_coordinacion TEXT;
UPDATE public.incapacidades i SET radicada_por=p.id_usuario FROM public.pacientes p WHERE p.id_paciente=i.id_paciente AND i.radicada_por IS NULL;
UPDATE public.incapacidades SET estado='Radicada' WHERE estado='En revisión';
UPDATE public.incapacidades SET estado='Rechazada por Coordinación' WHERE estado='Rechazada';
ALTER TABLE public.incapacidades ALTER COLUMN estado TYPE VARCHAR(40);
ALTER TABLE public.incapacidades DROP CONSTRAINT IF EXISTS incapacidades_estado_check;
ALTER TABLE public.incapacidades ADD CONSTRAINT incapacidades_estado_check CHECK (estado IN ('Radicada','Pendiente coordinación','Aprobada','Rechazada por Enfermería','Rechazada por Coordinación'));
CREATE INDEX IF NOT EXISTS idx_incapacidades_radicada_por ON public.incapacidades(radicada_por);
CREATE INDEX IF NOT EXISTS idx_incapacidades_estado ON public.incapacidades(estado);

-- Bucket privado para soportes de incapacidades
INSERT INTO storage.buckets(id,name,public,file_size_limit,allowed_mime_types)
VALUES('incapacidades','incapacidades',false,5242880,ARRAY['application/pdf','image/jpeg','image/png'])
ON CONFLICT(id) DO UPDATE SET public=false,file_size_limit=5242880,allowed_mime_types=EXCLUDED.allowed_mime_types;


-- =========================
-- IMPLEMENTOS DEPORTIVOS / BIENESTAR
-- =========================
CREATE TABLE IF NOT EXISTS public.implementos_deportivos (
    id_implemento BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(50) NOT NULL UNIQUE,
    nombre VARCHAR(120) NOT NULL,
    categoria VARCHAR(50) NOT NULL DEFAULT 'Otro',
    descripcion TEXT,
    cantidad_total INTEGER NOT NULL DEFAULT 1 CHECK (cantidad_total > 0),
    cantidad_disponible INTEGER NOT NULL DEFAULT 1 CHECK (cantidad_disponible >= 0),
    ubicacion VARCHAR(120),
    estado VARCHAR(20) NOT NULL DEFAULT 'Activo'
        CHECK (estado IN ('Activo','Mantenimiento','Inactivo')),
    fecha_registro TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    creado_por BIGINT REFERENCES public.usuarios(id_usuario) ON DELETE SET NULL,
    CONSTRAINT implementos_disponibilidad_check CHECK (cantidad_disponible <= cantidad_total)
);

CREATE TABLE IF NOT EXISTS public.prestamos_implementos (
    id_prestamo BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_implemento BIGINT NOT NULL REFERENCES public.implementos_deportivos(id_implemento) ON DELETE RESTRICT,
    id_estudiante BIGINT NOT NULL REFERENCES public.usuarios(id_usuario) ON DELETE RESTRICT,
    cantidad INTEGER NOT NULL DEFAULT 1 CHECK (cantidad > 0),
    fecha_prestamo TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    fecha_devolucion TIMESTAMPTZ,
    prestado_por BIGINT NOT NULL REFERENCES public.usuarios(id_usuario) ON DELETE RESTRICT,
    recibido_por BIGINT REFERENCES public.usuarios(id_usuario) ON DELETE SET NULL,
    observaciones_salida TEXT,
    observaciones_entrega TEXT,
    estado VARCHAR(20) NOT NULL DEFAULT 'Prestado'
        CHECK (estado IN ('Prestado','Devuelto','Cancelado')),
    CONSTRAINT prestamo_fechas_check CHECK (fecha_devolucion IS NULL OR fecha_devolucion >= fecha_prestamo)
);

CREATE INDEX IF NOT EXISTS idx_prestamos_implementos_estado ON public.prestamos_implementos(estado);
CREATE INDEX IF NOT EXISTS idx_prestamos_implementos_estudiante ON public.prestamos_implementos(id_estudiante);
CREATE INDEX IF NOT EXISTS idx_prestamos_implementos_item ON public.prestamos_implementos(id_implemento);
CREATE INDEX IF NOT EXISTS idx_prestamos_implementos_fecha ON public.prestamos_implementos(fecha_prestamo DESC);
