-- =========================================================
-- SISU - Base de datos PostgreSQL / Supabase
-- Conversión desde MariaDB
-- =========================================================

-- =========================
-- ROLES
-- =========================
CREATE TABLE public.roles (
    id_rol BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL,
    descripcion TEXT
);

-- =========================
-- USUARIOS
-- =========================
CREATE TABLE public.usuarios (
    id_usuario BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    correo VARCHAR(120) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    documento VARCHAR(30),
    telefono VARCHAR(30),
    id_rol BIGINT,
    estado VARCHAR(20) DEFAULT 'Activo'
        CHECK (estado IN ('Activo', 'Inactivo')),
    fecha_registro TIMESTAMPTZ DEFAULT NOW(),
    ultimo_acceso TIMESTAMPTZ,

    CONSTRAINT usuarios_id_rol_fkey
        FOREIGN KEY (id_rol)
        REFERENCES public.roles(id_rol)
        ON DELETE SET NULL
);

-- =========================
-- PACIENTES
-- =========================
CREATE TABLE public.pacientes (
    id_paciente BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario BIGINT UNIQUE,
    codigo_estudiantil VARCHAR(20) UNIQUE,
    programa_academico VARCHAR(100),
    semestre INTEGER,
    eps VARCHAR(100),
    tipo_sangre VARCHAR(10),
    contacto_emergencia VARCHAR(100),
    telefono_emergencia VARCHAR(30),
    alergias TEXT,

    CONSTRAINT pacientes_usuario_fkey
        FOREIGN KEY (id_usuario)
        REFERENCES public.usuarios(id_usuario)
        ON DELETE CASCADE
);

-- =========================
-- CONSULTAS
-- =========================
CREATE TABLE public.consultas (
    id_consulta BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_paciente BIGINT,
    id_profesional BIGINT,
    fecha TIMESTAMPTZ DEFAULT NOW(),
    motivo TEXT,
    sintomas TEXT,
    diagnostico TEXT,
    tratamiento TEXT,
    medicamentos TEXT,
    observaciones TEXT,

    tipo_consulta VARCHAR(30) DEFAULT 'Enfermería'
        CHECK (
            tipo_consulta IN (
                'Enfermería',
                'Medicina General'
            )
        ),

    signos_vitales TEXT,

    estado VARCHAR(20) DEFAULT 'Pendiente'
        CHECK (
            estado IN (
                'Pendiente',
                'Atendida',
                'Cancelada'
            )
        ),

    FOREIGN KEY (id_paciente)
        REFERENCES public.pacientes(id_paciente)
        ON DELETE CASCADE,

    FOREIGN KEY (id_profesional)
        REFERENCES public.usuarios(id_usuario)
        ON DELETE SET NULL
);

-- =========================
-- INCAPACIDADES
-- =========================
CREATE TABLE public.incapacidades (
    id_incapacidad BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_paciente BIGINT,
    id_consulta BIGINT,
    fecha_inicio DATE NOT NULL,
    fecha_fin DATE NOT NULL,
    dias_totales INTEGER,
    motivo TEXT,
    diagnostico TEXT,
    archivo_soporte VARCHAR(255),
    estado VARCHAR(40) DEFAULT 'Radicada' CHECK (estado IN ('Radicada','Pendiente coordinación','Aprobada','Rechazada por Enfermería','Rechazada por Coordinación')),
    observaciones TEXT,
    fecha_radicacion TIMESTAMPTZ DEFAULT NOW(),
    radicada_por BIGINT,
    revisada_enfermeria_por BIGINT,
    fecha_revision_enfermeria TIMESTAMPTZ,
    observacion_enfermeria TEXT,
    revisada_coordinacion_por BIGINT,
    fecha_revision_coordinacion TIMESTAMPTZ,
    observacion_coordinacion TEXT,
    fecha_aprobacion TIMESTAMPTZ,
    aprobado_por BIGINT,
    FOREIGN KEY (id_paciente) REFERENCES public.pacientes(id_paciente) ON DELETE CASCADE,
    FOREIGN KEY (id_consulta) REFERENCES public.consultas(id_consulta) ON DELETE SET NULL,
    FOREIGN KEY (radicada_por) REFERENCES public.usuarios(id_usuario) ON DELETE SET NULL,
    FOREIGN KEY (revisada_enfermeria_por) REFERENCES public.usuarios(id_usuario) ON DELETE SET NULL,
    FOREIGN KEY (revisada_coordinacion_por) REFERENCES public.usuarios(id_usuario) ON DELETE SET NULL,
    FOREIGN KEY (aprobado_por) REFERENCES public.usuarios(id_usuario) ON DELETE SET NULL
);

-- =========================
-- ACTIVIDADES DE BIENESTAR
-- =========================
CREATE TABLE public.actividades_bienestar (
    id_actividad BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR(150) NOT NULL,
    descripcion TEXT,

    categoria VARCHAR(30) DEFAULT 'Salud'
        CHECK (
            categoria IN (
                'Deportes',
                'Cultura',
                'Salud',
                'Recreación',
                'Formación'
            )
        ),

    fecha DATE NOT NULL,
    hora TIME NOT NULL,
    lugar VARCHAR(150),
    duracion_horas INTEGER DEFAULT 1,
    cupo_maximo INTEGER DEFAULT 30,
    cupos_disponibles INTEGER,
    responsable VARCHAR(100),
    requisitos TEXT,

    estado VARCHAR(20) DEFAULT 'Activa'
        CHECK (
            estado IN (
                'Activa',
                'Completa',
                'Finalizada',
                'Cancelada'
            )
        ),

    fecha_creacion TIMESTAMPTZ DEFAULT NOW()
);

-- =========================
-- INSCRIPCIONES BIENESTAR
-- =========================
CREATE TABLE public.inscripciones_bienestar (
    id_inscripcion BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_actividad BIGINT,
    id_usuario BIGINT,
    fecha_inscripcion TIMESTAMPTZ DEFAULT NOW(),
    asistio BOOLEAN DEFAULT FALSE,

    calificacion INTEGER
        CHECK (calificacion >= 1 AND calificacion <= 5),

    comentarios TEXT,

    estado VARCHAR(20) DEFAULT 'Inscrito'
        CHECK (
            estado IN (
                'Inscrito',
                'Confirmado',
                'Cancelado',
                'Asistió'
            )
        ),

    CONSTRAINT unique_inscripcion
        UNIQUE (id_actividad, id_usuario),

    FOREIGN KEY (id_actividad)
        REFERENCES public.actividades_bienestar(id_actividad)
        ON DELETE CASCADE,

    FOREIGN KEY (id_usuario)
        REFERENCES public.usuarios(id_usuario)
        ON DELETE CASCADE
);

-- =========================
-- INVENTARIO
-- =========================
CREATE TABLE public.inventario (
    id_inventario BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(50),
    nombre VARCHAR(150) NOT NULL,
    descripcion TEXT,
    categoria VARCHAR(100),
    cantidad INTEGER NOT NULL DEFAULT 0,
    cantidad_minima INTEGER NOT NULL DEFAULT 0,
    ubicacion VARCHAR(100),
    proveedor VARCHAR(150),
    fecha_vencimiento DATE,
    lote VARCHAR(50),
    costo_unitario NUMERIC(10,2),
    estado VARCHAR(20) DEFAULT 'Disponible'
);

-- =========================
-- MOVIMIENTOS INVENTARIO
-- =========================
CREATE TABLE public.movimiento_inventario (
    id_movimiento BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_inventario BIGINT NOT NULL,
    tipo VARCHAR(20) NOT NULL,
    cantidad INTEGER NOT NULL,
    motivo VARCHAR(255),
    usuario_id BIGINT,
    fecha_movimiento TIMESTAMPTZ DEFAULT NOW(),

    FOREIGN KEY (id_inventario)
        REFERENCES public.inventario(id_inventario)
        ON DELETE CASCADE,

    FOREIGN KEY (usuario_id)
        REFERENCES public.usuarios(id_usuario)
        ON DELETE SET NULL
);

-- =========================
-- ACOMPAÑAMIENTOS
-- =========================
CREATE TABLE public.acompanamientos (
    id_acompanamiento BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_paciente BIGINT NOT NULL,
    usuario_id BIGINT NOT NULL,
    motivo VARCHAR(255) NOT NULL,
    estado VARCHAR(20) NOT NULL DEFAULT 'Activo',
    fecha_inicio TIMESTAMPTZ DEFAULT NOW(),
    fecha_cierre TIMESTAMPTZ,

    FOREIGN KEY (id_paciente)
        REFERENCES public.pacientes(id_paciente)
        ON DELETE CASCADE,

    FOREIGN KEY (usuario_id)
        REFERENCES public.usuarios(id_usuario)
        ON DELETE CASCADE
);

-- =========================
-- SEGUIMIENTOS
-- =========================
CREATE TABLE public.seguimientos_acompanamiento (
    id_seguimiento BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_acompanamiento BIGINT NOT NULL,
    usuario_id BIGINT NOT NULL,
    fecha_contacto TIMESTAMPTZ DEFAULT NOW(),
    tipo_contacto VARCHAR(20) NOT NULL,
    notas TEXT NOT NULL,
    estado VARCHAR(20) NOT NULL,
    proxima_fecha DATE,

    FOREIGN KEY (id_acompanamiento)
        REFERENCES public.acompanamientos(id_acompanamiento)
        ON DELETE CASCADE,

    FOREIGN KEY (usuario_id)
        REFERENCES public.usuarios(id_usuario)
        ON DELETE CASCADE
);

-- =========================
-- ÍNDICES
-- =========================
CREATE INDEX idx_usuarios_rol
ON public.usuarios(id_rol);

CREATE INDEX idx_consultas_paciente
ON public.consultas(id_paciente);

CREATE INDEX idx_consultas_profesional
ON public.consultas(id_profesional);

CREATE INDEX idx_incapacidades_paciente
ON public.incapacidades(id_paciente);

CREATE INDEX idx_acompanamientos_paciente
ON public.acompanamientos(id_paciente);

CREATE INDEX idx_movimientos_inventario
ON public.movimiento_inventario(id_inventario);


INSERT INTO public.roles
(id_rol, nombre, descripcion)
OVERRIDING SYSTEM VALUE
VALUES
(1, 'Administrador', 'Acceso total al sistema'),
(2, 'Coordinador', 'Coordina actividades y aprueba incapacidades'),
(3, 'Estudiante', 'Acceso a servicios de salud y bienestar'),
(4, 'Enfermero', 'Gestiona consultas de enfermería'),
(5, 'Docente', 'Visualiza incapacidades de sus estudiantes'),
(7, 'Bienestar', 'Gestiona actividades de bienestar estudiantil');